In [ ]:
import numpy as np
import pandas as pd

In [50]:
df = pd.read_csv('cars.csv')

In [51]:
df.head()

     brand     model  year  engine_size fuel_type transmission  mileage  price
0   Toyota   Corolla  2018          1.8    Petrol    Automatic    45000  15000
1    Honda     Civic  2020          2.0    Petrol       Manual    30000  20000
2     Ford     Focus  2017          1.5    Diesel       Manual    60000  12000
3      BMW  3 Series  2019          2.0    Petrol    Automatic    35000  28000
4  Hyundai   Elantra  2021          2.0    Petrol    Automatic    15000  22000

In [52]:
df['brand'].value_counts()

brand
Toyota        1
Honda         1
Ford          1
BMW           1
Hyundai       1
Kia           1
Tesla         1
Nissan        1
Chevrolet     1
Volkswagen    1
Name: count, dtype: int64

In [56]:
df['fuel_type'].nunique()

3

### OneHotEncoding using Pandas

In [58]:
pd.get_dummies(df,columns=['fuel_type','brand'])

,model,year,engine_size,transmission,mileage,price,fuel_type_Diesel,fuel_type_Electric,fuel_type_Petrol,brand_BMW,brand_Chevrolet,brand_Ford,brand_Honda,brand_Hyundai,brand_Kia,brand_Nissan,brand_Tesla,brand_Toyota,brand_Volkswagen
0,Corolla,2018,1.8,Automatic,45000,15000,False,False,True,False,False,False,False,False,False,False,False,True,False
1,Civic,2020,2.0,Manual,30000,20000,False,False,True,False,False,False,True,False,False,False,False,False,False
2,Focus,2017,1.5,Manual,60000,12000,True,False,False,False,False,True,False,False,False,False,False,False,False
3,3 Series,2019,2.0,Automatic,35000,28000,False,False,True,True,False,False,False,False,False,False,False,False,False
4,Elantra,2021,2.0,Automatic,15000,22000,False,False,True,False,False,False,False,True,False,False,False,False,False
5,Rio,2016,1.4,Manual,70000,9000,False,False,True,False,False,False,False,False,True,False,False,False,False
6,Model 3,2022,0.0,Automatic,10000,40000,False,True,False,False,False,False,False,False,False,False,True,False,False
7,Altima,2018,2.5,Automatic,50000,16000,False,False,True,False,False,False,False,False,False,True,False,False,False
8,Cruze,2017,1.6,Manual,65000,11000,True,False,False,False,True,False,False,False,False,False,False,False,False
9,Golf,2019,1.4,Automatic,40000,18000,False,False,True,False,False,False,False,False,False,False,False,False,True

K-1 oneHotEncoding

In [59]:
pd.get_dummies(df[['fuel_type','brand']],drop_first=True)

,fuel_type_Electric,fuel_type_Petrol,brand_Chevrolet,brand_Ford,brand_Honda,brand_Hyundai,brand_Kia,brand_Nissan,brand_Tesla,brand_Toyota,brand_Volkswagen
0,False,True,False,False,False,False,False,False,False,True,False
1,False,True,False,False,True,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,False
4,False,True,False,False,False,True,False,False,False,False,False
5,False,True,False,False,False,False,True,False,False,False,False
6,True,False,False,False,False,False,False,False,True,False,False
7,False,True,False,False,False,False,False,True,False,False,False
8,False,False,True,False,False,False,False,False,False,False,False
9,False,True,False,False,False,False,False,False,False,False,True

###OneHotEncoding using Skelearn

In [63]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:6],df.iloc[:,6],test_size=0.2,random_state=0)

In [65]:
X_test.head()

       brand  model  year  engine_size fuel_type transmission
2       Ford  Focus  2017          1.5    Diesel       Manual
8  Chevrolet  Cruze  2017          1.6    Diesel       Manual

In [76]:
from sklearn.preprocessing import OneHotEncoder

In [90]:
ohe = OneHotEncoder(drop='first')

In [95]:
X_train_new = ohe.fit_transform(X_train[['fuel_type','transmission']]).toarray()

In [94]:
X_test_new = ohe.transform(X_test[['fuel_type','transmission']]).toarray()

NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [91]:
X_train_new

array([[0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.]])

In [93]:
np.hstack((X_train[['brand','model']].values,X_train_new)).shape

(8, 6)

### OneHotEncoding with top categories

In [101]:
df['brand'].value_counts()

brand
Toyota        1
Honda         1
Ford          1
BMW           1
Hyundai       1
Kia           1
Tesla         1
Nissan        1
Chevrolet     1
Volkswagen    1
Name: count, dtype: int64

In [108]:
df['brand'].nunique()
threshold = 100

In [ ]:
repl = counts [counts <= threshold].index

NameError: name 'counts' is not defined

In [107]:
pd.get_dummies(df['fuel_type']).replace(repl,'uncommon')

NameError: name 'repl' is not defined