In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("covid_toy.csv")

In [5]:
df.head()

   age  fever  gender cough       city has_covid
0   25      1    Male   Yes  Kathmandu  Positive
1   40      0  Female    No   Lalitpur  Negative
2   30      1    Male   Yes  Bhaktapur  Positive
3   22      0  Female    No    Pokhara  Negative
4   35      1    Male   Yes  Kathmandu  Positive

In [6]:
df.isnull().sum()

age          0
fever        0
gender       0
cough        0
city         0
has_covid    0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df["has_covid"], test_size=0.2, random_state=42)

In [8]:
X_train.head()

    age  fever  gender cough        city
13   41      0  Female    No  Biratnagar
5    28      0  Female   Yes    Lalitpur
8    45      1    Male   Yes     Pokhara
2    30      1    Male   Yes   Bhaktapur
1    40      0  Female    No    Lalitpur